### PR TITLE
Fixed sphere geometry kind

### PR DESCRIPTION
**Pull request by minorai**
This PR should fix sphere geometry being incorrectly marked as a cylinder.

### CODE REVIEW

**Comment by hbssessa** [comment]
Dear Minorai,
I saw that you worked with this code recently.
I am trying to use this code to parse a rvm file. However, I got the following error:

Failed to parse PDMS.rvm: In CNTB, unknown chunk id INSU
[I] Stats:
[I] Groups 593
[I] Geometries 570 (grp avg=1.0)
[I] Pyramids 0
[I] Boxes 0
[I] Rectangular tori 0
[I] Circular tori 252
[I] Elliptical dish 0
[I] Spherical dish 0
[I] Snouts 4
[I] Cylinders 314
[I] Spheres 0
[I] Facet groups 0
[I] triangles 0
[I] quads 0
[I] polygons 0 (fgrp avg=-nan(ind))
[I] contours 0 (poly avg=-nan(ind))
[I] vertices 0 (cont avg=-nan(ind))
[I] Lines 0

as far as I understood, INSU is something which is parsed ParseRVM.cpp between the lines 302-317.
Do you have any idea on how to skip this specific ID or parse it?
Your support would be of great help, thank you very much in advance.

Best regards
Salvo

**Comment by minorai** [comment]
Hi Salvo,

Unfortunately I will not be able to help you. I am not familiar with INSU chunks (and I do not have any files that contain this type of data). A procedure to skip a chunk would depend on its structure (size, start/end label, whenever it can contain sub chunks). You might want to inspect the file content manually (in a hex viewer) and try to see where the chunks start and ends, whenever it is a constant size or if it has a variable length.

Best regards,
Georgy

**Comment by hbssessa** [comment]
Dear Georgy,

I inspected with hex as you suggested and the INSU (which is the chunk for insulation in pipes) unfortunately is not constant.
Could you please suggest a way to skip bytes until the next valid chunk. I am sorry but I am not very familiar with the logic of this parser.
Is there already a function to read group of 32 * 4 bytes and check if it is a valid chunk and if not then just to skip one byte? I think doing that recursively should be fine to skip the chunk. Later I can try to understand the type of insulation. Do you have any thoughts?

Cheers
--
Salvo

**Comment by minorai** [comment]
Well, I have another idea. My guess is that INSU is similar to PRIM (geometry chunk). A header is usually followed by two fields (see parse_chunk_header function). One parameter is labeled **len** and another **dunno**. I think that len is a bit incorrect name. What it actually specifies is an offset of the next chunk from the start of the file. So you could use this value to skip chunks until you hit something that is supported by the parser.

```c++  
const char* parse_chunk_header(char* id, uint32_t& len, uint32_t& dunno, const char* p, const char* e)
  {
    unsigned i = 0;
    for (i = 0; i < 4 && p + 4 <= e; i++) {
      assert(p[0] == 0);
      assert(p[1] == 0);
      assert(p[2] == 0);
      id[i] = p[3];
      p += 4;
    }
    for (; i < 4; i++) {
      id[i] = ' ';
    }
    if (p + 8 <= e) {
      p = read_uint32_be(len, p, e);
      p = read_uint32_be(dunno, p, e);
    }
    else {
      len = ~0;
      dunno = ~0;
      fprintf(stderr, "Chunk '%s' EOF after %zd bytes\n", id, e - p);
      p = e;
    }
    return p;
  }
```

Here is an example of PRIM chunk start with next chunk offset set at 0x0808, and at address 0x0808 we can see the CNTE tag, that end the group that PRIM belongs to.
image

**Comment by hbssessa** [comment]
That's a nice idea! I will try to implement it.

**Review by cdyk — APPROVED** [review]
Thanks

**Comment by cdyk** [comment]
> 
> 
> Well, I have another idea. My guess is that INSU is similar to PRIM (geometry chunk). A header is usually followed by two fields (see parse_chunk_header function). One parameter is labeled **len** and another **dunno**. I think that len is a bit incorrect name. What it actually specifies is an offset of the next chunk from the start of the file. So you could use this value to skip chunks until you hit something that is supported by the parser.
> 
> ```c++
> const char* parse_chunk_header(char* id, uint32_t& len, uint32_t& dunno, const char* p, const char* e)
>   {
>     unsigned i = 0;
>     for (i = 0; i < 4 && p + 4 <= e; i++) {
>       assert(p[0] == 0);
>       assert(p[1] == 0);
>       assert(p[2] == 0);
>       id[i] = p[3];
>       p += 4;
>     }
>     for (; i < 4; i++) {
>       id[i] = ' ';
>     }
>     if (p + 8 <= e) {
>       p = read_uint32_be(len, p, e);
>       p = read_uint32_be(dunno, p, e);
>     }
>     else {
>       len = ~0;
>       dunno = ~0;
>       fprintf(stderr, "Chunk '%s' EOF after %zd bytes\n", id, e - p);
>       p = e;
>     }
>     return p;
>   }
> ```
> 
> Here is an example of PRIM chunk start with next chunk offset set at 0x0808, and at address 0x0808 we can see the CNTE tag, that end the group that PRIM belongs to.
> image

I missed that one, I'll fix the naming of len to offset and add skipping of INSU sections. Thanks!

**Pull request merged**
