### PR TITLE
Gltf merge meshes

### PR DESCRIPTION
**Pull request by cdyk**
Add option to merge geometries below a node instead of creating a lot of anonymous nodes.

### CODE REVIEW

**Comment by VegarRingdalAibel** [comment]
This might be useful on some files, especially if its rvm files with STEP files imported.

**Comment by VegarRingdalAibel** [comment]
For viewing files, and option to just merge per color might be practical also, since standard glb viewers will use a very long time to open a file with a lot of items.
Could maybe have additional meta with three data, on names with geometry it would be useful vertex groups (buffer/index/count) it belongs too.

**Comment by cdyk** [comment]
To just optimize rendering, [GLTFPack](https://meshoptimizer.org/) is something to try. I think it merges meshes by material by default.

**Comment by cdyk** [comment]
RVM files can have multiple geometries below a hierarchy node, and each of these geometries have a transform. But transforms can only be attached to nodes in GLTF not to geometries (or primitives which it is called), so the previous code just added a dummy node to hold the transform.

This code here tries to avoid this when there is only one geometry, and if merging is enabled and there are multiple geometries below, they are transformed into a common frame so they use the same transform, and there is no need to add an extra holder node.

However, it will only simplify the hierarchy by avoiding creating more hierarchy than there is. But in rvm files there are typically a lot of uninteresting hierarchy like "CYLINDER 1 OF FOO of BAR" etc, and removing that is probably better handled by a dedicated prune step that just collapses everything that has a name that doesn't match a regex or something, then all the exports like gltf and json matches in structure

**Comment by cdyk** [comment]
It appears to be working, feel free to try it out. I will merge it when I have tested it a bit more thoroughly.

**Pull request merged**
